name: User API CI

on:
  pull_request:
    paths:
      - 'user-api/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - '.eslintrc*'
      - 'jest.base.config.ts'
      - 'tools/**'
  push:
    branches:
      - main
    paths:
      - 'user-api/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - '.eslintrc*'
      - 'jest.base.config.ts'
      - 'tools/**'

jobs:
  pact-flow:
    # Wait for pact-flow workflow to complete successfully
    # This ensures contracts are verified and mocks are generated
    uses: ./.github/workflows/pact-flow.yml

  user-tests:
    needs: pact-flow
    # Unit and integration tests for user-api
    uses: ./.github/workflows/_node-ci.yml
    with:
      workspace: 'user-api'
      run_coverage: true
    secrets: inherit
